name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Debug - List generated files
        run: ls -R html || echo "No HTML files found"

      - name: Upload Doxygen output as artifact (for debugging)
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-html
          path: html

      - name: Deploy to GitHub Pages
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: html
          config_file: Doxyfile
          doxygen_version: 1.9.6

      - name: Commit and push to gh-pages manually
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          cp -r ../html/* .
          git add .
          git commit -m "Update Doxygen documentation"
          git push origin gh-pages
