name: Deploy Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Documentation
        run: doxygen ./Doxyfile

      - name: Upload Artifact for Pages Deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
